name: Creación html
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  # Ejecutar cada 20 minutos

  # # Ejecutar en push events
  # push:
  #   branches: [ main ]

  # # Ejecutar en pull request events
  # pull_request:
  #   types: [opened, synchronize]

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
#    - name: Checkout del código
#      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/checkout@v4
      with:
        #python-version: '3.x'
        
        python-version: '3.11'
    

    - name: Instalar dependencias
      run: |
        python -m pip install setuptools
        python -m pip install --upgrade pip
        pip install -r requirements.txt         

    - name: Ejecutar script Python
      run: |
        #python Download_data.py
        python Thermal_map_html_creation.py

    - name:  Commit de los cambios en el repositorio
      run: |  
        git config --global user.email "francisco.corvalan6@gmail.com"
        git config --global user.name "francorvalan"
#        git add .
#        git commit -m "sitio web generado con último valor estimado de turbidez"
#        git push origin main

    - name: autocomit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Changed files
        push_options: '--force'
    
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: ${{ github.ref }}
    # - uses: fastify/github-action-merge-dependabot@v2.1.1
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
